2024-08-16 17:52:25,827 INFO    MainThread:2762947 [wandb_setup.py:_flush():76] Current SDK version is 0.17.1
2024-08-16 17:52:25,827 INFO    MainThread:2762947 [wandb_setup.py:_flush():76] Configure stats pid to 2762947
2024-08-16 17:52:25,827 INFO    MainThread:2762947 [wandb_setup.py:_flush():76] Loading settings from /cluster/home/pgoyal/.config/wandb/settings
2024-08-16 17:52:25,827 INFO    MainThread:2762947 [wandb_setup.py:_flush():76] Loading settings from /cluster/home/pgoyal/main/test/wandb/settings
2024-08-16 17:52:25,827 INFO    MainThread:2762947 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-08-16 17:52:25,827 INFO    MainThread:2762947 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-08-16 17:52:25,827 INFO    MainThread:2762947 [wandb_setup.py:_flush():76] Applying login settings: {'api_key': '***REDACTED***'}
2024-08-16 17:52:25,827 INFO    MainThread:2762947 [wandb_setup.py:_flush():76] Applying login settings: {'api_key': '***REDACTED***'}
2024-08-16 17:52:25,827 INFO    MainThread:2762947 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-08-16 17:52:25,827 INFO    MainThread:2762947 [wandb_init.py:_log_setup():520] Logging user logs to /cluster/home/pgoyal/main/test/wandb/run-20240816_175225-xbbsyh0t/logs/debug.log
2024-08-16 17:52:25,828 INFO    MainThread:2762947 [wandb_init.py:_log_setup():521] Logging internal logs to /cluster/home/pgoyal/main/test/wandb/run-20240816_175225-xbbsyh0t/logs/debug-internal.log
2024-08-16 17:52:25,828 INFO    MainThread:2762947 [wandb_init.py:_jupyter_setup():466] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x14b6a09ec0d0>
2024-08-16 17:52:25,828 INFO    MainThread:2762947 [wandb_init.py:init():560] calling init triggers
2024-08-16 17:52:25,828 INFO    MainThread:2762947 [wandb_init.py:init():567] wandb.init called with sweep_config: {}
config: {}
2024-08-16 17:52:25,828 INFO    MainThread:2762947 [wandb_init.py:init():610] starting backend
2024-08-16 17:52:25,828 INFO    MainThread:2762947 [wandb_init.py:init():614] setting up manager
2024-08-16 17:52:25,833 INFO    MainThread:2762947 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: fork
2024-08-16 17:52:25,834 INFO    MainThread:2762947 [wandb_init.py:init():622] backend started and connected
2024-08-16 17:52:25,840 INFO    MainThread:2762947 [wandb_run.py:_label_probe_notebook():1334] probe notebook
2024-08-16 17:52:25,840 INFO    MainThread:2762947 [wandb_run.py:_label_probe_notebook():1344] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-08-16 17:52:25,840 INFO    MainThread:2762947 [wandb_init.py:init():711] updated telemetry
2024-08-16 17:52:25,841 INFO    MainThread:2762947 [wandb_init.py:init():744] communicating run to backend with 90.0 second timeout
2024-08-16 17:53:55,914 ERROR   MainThread:2762947 [wandb_init.py:init():770] encountered error: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2024-08-16 17:53:55,915 ERROR   MainThread:2762947 [wandb_init.py:init():1181] error in wandb.init()
Traceback (most recent call last):
  File "/cluster/software/stacks/2024-05/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-13.2.0/python-3.11.6-m4n2ny4dwaqmeobuqquo3gpyw2bct67i/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1171, in init
    return wi.init()
           ^^^^^^^^^
  File "/cluster/software/stacks/2024-05/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-13.2.0/python-3.11.6-m4n2ny4dwaqmeobuqquo3gpyw2bct67i/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 776, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2024-08-16 17:54:03,294 INFO    MainThread:2762947 [wandb_settings.py:_apply_login():1911] Applying login settings: {'api_key': '***REDACTED***'}
2024-08-16 17:54:03,306 INFO    MainThread:2762947 [wandb_settings.py:_apply_login():1911] Applying login settings: {'api_key': '***REDACTED***'}
2024-08-16 17:54:06,337 INFO    MainThread:2762947 [wandb_settings.py:_apply_login():1911] Applying login settings: {'api_key': '***REDACTED***'}
2024-08-16 17:54:06,346 INFO    MainThread:2762947 [wandb_settings.py:_apply_login():1911] Applying login settings: {'api_key': '***REDACTED***'}
2024-08-16 17:54:10,679 INFO    MainThread:2762947 [wandb_settings.py:_apply_login():1911] Applying login settings: {}
2024-08-16 17:54:10,692 INFO    MainThread:2762947 [wandb_setup.py:_flush():76] Current SDK version is 0.17.1
2024-08-16 17:54:10,692 INFO    MainThread:2762947 [wandb_setup.py:_flush():76] Configure stats pid to 2762947
2024-08-16 17:54:10,693 INFO    MainThread:2762947 [wandb_setup.py:_flush():76] Loading settings from /cluster/home/pgoyal/.config/wandb/settings
2024-08-16 17:54:10,693 INFO    MainThread:2762947 [wandb_setup.py:_flush():76] Loading settings from /cluster/home/pgoyal/main/test/wandb/settings
2024-08-16 17:54:10,693 INFO    MainThread:2762947 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-08-16 17:54:10,693 INFO    MainThread:2762947 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-08-16 17:54:10,693 INFO    MainThread:2762947 [wandb_setup.py:_flush():76] Applying login settings: {'api_key': '***REDACTED***'}
2024-08-16 17:54:10,693 INFO    MainThread:2762947 [wandb_setup.py:_flush():76] Applying login settings: {'api_key': '***REDACTED***'}
2024-08-16 17:54:10,693 INFO    MainThread:2762947 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-08-16 17:54:10,693 INFO    MainThread:2762947 [wandb_init.py:_log_setup():520] Logging user logs to /cluster/home/pgoyal/main/test/wandb/run-20240816_175410-4qgg9daf/logs/debug.log
2024-08-16 17:54:10,694 INFO    MainThread:2762947 [wandb_init.py:_log_setup():521] Logging internal logs to /cluster/home/pgoyal/main/test/wandb/run-20240816_175410-4qgg9daf/logs/debug-internal.log
2024-08-16 17:54:10,694 INFO    MainThread:2762947 [wandb_init.py:init():560] calling init triggers
2024-08-16 17:54:10,694 INFO    MainThread:2762947 [wandb_init.py:init():567] wandb.init called with sweep_config: {}
config: {}
2024-08-16 17:54:10,694 INFO    MainThread:2762947 [wandb_init.py:init():610] starting backend
2024-08-16 17:54:10,694 INFO    MainThread:2762947 [wandb_init.py:init():614] setting up manager
2024-08-16 17:54:10,702 INFO    MainThread:2762947 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: fork
2024-08-16 17:54:10,703 INFO    MainThread:2762947 [wandb_init.py:init():622] backend started and connected
2024-08-16 17:54:10,710 INFO    MainThread:2762947 [wandb_run.py:_label_probe_notebook():1334] probe notebook
2024-08-16 17:54:10,711 INFO    MainThread:2762947 [wandb_run.py:_label_probe_notebook():1344] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-08-16 17:54:10,711 INFO    MainThread:2762947 [wandb_init.py:init():711] updated telemetry
2024-08-16 17:54:10,712 INFO    MainThread:2762947 [wandb_init.py:init():744] communicating run to backend with 90.0 second timeout
2024-08-16 17:54:14,091 WARNING MainThread:2762947 [wandb_init.py:init():1175] interrupted
Traceback (most recent call last):
  File "/cluster/software/stacks/2024-05/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-13.2.0/python-3.11.6-m4n2ny4dwaqmeobuqquo3gpyw2bct67i/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1171, in init
    return wi.init()
           ^^^^^^^^^
  File "/cluster/software/stacks/2024-05/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-13.2.0/python-3.11.6-m4n2ny4dwaqmeobuqquo3gpyw2bct67i/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 747, in init
    result = run_init_handle.wait(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/software/stacks/2024-05/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-13.2.0/python-3.11.6-m4n2ny4dwaqmeobuqquo3gpyw2bct67i/lib/python3.11/site-packages/wandb/sdk/lib/mailbox.py", line 283, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/software/stacks/2024-05/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-13.2.0/python-3.11.6-m4n2ny4dwaqmeobuqquo3gpyw2bct67i/lib/python3.11/site-packages/wandb/sdk/lib/mailbox.py", line 130, in _get_and_clear
    if self._wait(timeout=timeout):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/software/stacks/2024-05/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-13.2.0/python-3.11.6-m4n2ny4dwaqmeobuqquo3gpyw2bct67i/lib/python3.11/site-packages/wandb/sdk/lib/mailbox.py", line 126, in _wait
    return self._event.wait(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/software/stacks/2024-05/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-13.2.0/python-3.11.6-m4n2ny4dwaqmeobuqquo3gpyw2bct67i/lib/python3.11/threading.py", line 629, in wait
    signaled = self._cond.wait(timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/software/stacks/2024-05/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-13.2.0/python-3.11.6-m4n2ny4dwaqmeobuqquo3gpyw2bct67i/lib/python3.11/threading.py", line 331, in wait
    gotit = waiter.acquire(True, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
2024-08-16 17:54:20,863 INFO    MainThread:2762947 [wandb_settings.py:_apply_login():1911] Applying login settings: {}
2024-08-16 17:54:20,873 INFO    MainThread:2762947 [wandb_setup.py:_flush():76] Current SDK version is 0.17.1
2024-08-16 17:54:20,873 INFO    MainThread:2762947 [wandb_setup.py:_flush():76] Configure stats pid to 2762947
2024-08-16 17:54:20,874 INFO    MainThread:2762947 [wandb_setup.py:_flush():76] Loading settings from /cluster/home/pgoyal/.config/wandb/settings
2024-08-16 17:54:20,874 INFO    MainThread:2762947 [wandb_setup.py:_flush():76] Loading settings from /cluster/home/pgoyal/main/test/wandb/settings
2024-08-16 17:54:20,874 INFO    MainThread:2762947 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-08-16 17:54:20,874 INFO    MainThread:2762947 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-08-16 17:54:20,874 INFO    MainThread:2762947 [wandb_setup.py:_flush():76] Applying login settings: {'api_key': '***REDACTED***'}
2024-08-16 17:54:20,874 INFO    MainThread:2762947 [wandb_setup.py:_flush():76] Applying login settings: {'api_key': '***REDACTED***'}
2024-08-16 17:54:20,874 INFO    MainThread:2762947 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-08-16 17:54:20,874 INFO    MainThread:2762947 [wandb_init.py:_log_setup():520] Logging user logs to /cluster/home/pgoyal/main/test/wandb/run-20240816_175420-y7y1vnha/logs/debug.log
2024-08-16 17:54:20,874 INFO    MainThread:2762947 [wandb_init.py:_log_setup():521] Logging internal logs to /cluster/home/pgoyal/main/test/wandb/run-20240816_175420-y7y1vnha/logs/debug-internal.log
2024-08-16 17:54:20,875 INFO    MainThread:2762947 [wandb_init.py:init():560] calling init triggers
2024-08-16 17:54:20,875 INFO    MainThread:2762947 [wandb_init.py:init():567] wandb.init called with sweep_config: {}
config: {}
2024-08-16 17:54:20,875 INFO    MainThread:2762947 [wandb_init.py:init():610] starting backend
2024-08-16 17:54:20,875 INFO    MainThread:2762947 [wandb_init.py:init():614] setting up manager
2024-08-16 17:54:20,880 INFO    MainThread:2762947 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-08-16 17:54:20,881 INFO    MainThread:2762947 [wandb_init.py:init():622] backend started and connected
2024-08-16 17:54:20,888 INFO    MainThread:2762947 [wandb_run.py:_label_probe_notebook():1334] probe notebook
2024-08-16 17:54:20,888 INFO    MainThread:2762947 [wandb_run.py:_label_probe_notebook():1344] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-08-16 17:54:20,888 INFO    MainThread:2762947 [wandb_init.py:init():711] updated telemetry
2024-08-16 17:54:20,890 INFO    MainThread:2762947 [wandb_init.py:init():744] communicating run to backend with 90.0 second timeout
2024-08-16 17:55:50,958 ERROR   MainThread:2762947 [wandb_init.py:init():770] encountered error: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2024-08-16 17:55:50,959 ERROR   MainThread:2762947 [wandb_init.py:init():1181] error in wandb.init()
Traceback (most recent call last):
  File "/cluster/software/stacks/2024-05/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-13.2.0/python-3.11.6-m4n2ny4dwaqmeobuqquo3gpyw2bct67i/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1171, in init
    return wi.init()
           ^^^^^^^^^
  File "/cluster/software/stacks/2024-05/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-13.2.0/python-3.11.6-m4n2ny4dwaqmeobuqquo3gpyw2bct67i/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 776, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2024-08-16 17:57:02,525 INFO    MainThread:2762947 [wandb_settings.py:_apply_login():1911] Applying login settings: {'api_key': '***REDACTED***'}
2024-08-16 17:57:02,538 INFO    MainThread:2762947 [wandb_settings.py:_apply_login():1911] Applying login settings: {'api_key': '***REDACTED***'}
2024-08-16 17:57:08,359 INFO    MainThread:2762947 [wandb_settings.py:_apply_login():1911] Applying login settings: {}
2024-08-16 17:57:08,371 INFO    MainThread:2762947 [wandb_setup.py:_flush():76] Current SDK version is 0.17.1
2024-08-16 17:57:08,372 INFO    MainThread:2762947 [wandb_setup.py:_flush():76] Configure stats pid to 2762947
2024-08-16 17:57:08,372 INFO    MainThread:2762947 [wandb_setup.py:_flush():76] Loading settings from /cluster/home/pgoyal/.config/wandb/settings
2024-08-16 17:57:08,372 INFO    MainThread:2762947 [wandb_setup.py:_flush():76] Loading settings from /cluster/home/pgoyal/main/test/wandb/settings
2024-08-16 17:57:08,372 INFO    MainThread:2762947 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-08-16 17:57:08,372 INFO    MainThread:2762947 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-08-16 17:57:08,372 INFO    MainThread:2762947 [wandb_setup.py:_flush():76] Applying login settings: {'api_key': '***REDACTED***'}
2024-08-16 17:57:08,372 INFO    MainThread:2762947 [wandb_setup.py:_flush():76] Applying login settings: {'api_key': '***REDACTED***'}
2024-08-16 17:57:08,372 INFO    MainThread:2762947 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-08-16 17:57:08,372 INFO    MainThread:2762947 [wandb_init.py:_log_setup():520] Logging user logs to /cluster/home/pgoyal/main/test/wandb/run-20240816_175708-dz5thj2n/logs/debug.log
2024-08-16 17:57:08,372 INFO    MainThread:2762947 [wandb_init.py:_log_setup():521] Logging internal logs to /cluster/home/pgoyal/main/test/wandb/run-20240816_175708-dz5thj2n/logs/debug-internal.log
2024-08-16 17:57:08,372 INFO    MainThread:2762947 [wandb_init.py:init():560] calling init triggers
2024-08-16 17:57:08,372 INFO    MainThread:2762947 [wandb_init.py:init():567] wandb.init called with sweep_config: {}
config: {}
2024-08-16 17:57:08,373 INFO    MainThread:2762947 [wandb_init.py:init():610] starting backend
2024-08-16 17:57:08,373 INFO    MainThread:2762947 [wandb_init.py:init():614] setting up manager
2024-08-16 17:57:08,380 INFO    MainThread:2762947 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: fork
2024-08-16 17:57:08,381 INFO    MainThread:2762947 [wandb_init.py:init():622] backend started and connected
2024-08-16 17:57:08,387 INFO    MainThread:2762947 [wandb_run.py:_label_probe_notebook():1334] probe notebook
2024-08-16 17:57:08,387 INFO    MainThread:2762947 [wandb_run.py:_label_probe_notebook():1344] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-08-16 17:57:08,387 INFO    MainThread:2762947 [wandb_init.py:init():711] updated telemetry
2024-08-16 17:57:08,388 INFO    MainThread:2762947 [wandb_init.py:init():744] communicating run to backend with 90.0 second timeout
2024-08-16 17:58:38,455 ERROR   MainThread:2762947 [wandb_init.py:init():770] encountered error: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2024-08-16 17:58:38,457 ERROR   MainThread:2762947 [wandb_init.py:init():1181] error in wandb.init()
Traceback (most recent call last):
  File "/cluster/software/stacks/2024-05/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-13.2.0/python-3.11.6-m4n2ny4dwaqmeobuqquo3gpyw2bct67i/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1171, in init
    return wi.init()
           ^^^^^^^^^
  File "/cluster/software/stacks/2024-05/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-13.2.0/python-3.11.6-m4n2ny4dwaqmeobuqquo3gpyw2bct67i/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 776, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
